export const domainsConstants = {
    GET_DOMAIN: "GET_DOMAIN",
    GET_DOMAIN_SUCCESS: "GET_DOMAIN_SUCCESS",
    GET_DOMAIN_FAILURE: "GET_DOMAIN_FAILURE",
    GET_DOMAIN_UPDATE_ITEM: "GET_DOMAIN_UPDATE_ITEM"
}
